# .github/workflows/ci.yml
name: Flutter CI

on:
  push:
    branches: [ dev ]

env:
  JAVA_VERSION: 12.x
  FLUTTER_VERSION: 1.22.4
  TEST_OUTPUT_DIR: test-reports

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Set up test environment
        run: |
          flutter pub get
          flutter pub global activate dart_dot_reporter
          flutter pub global activate junitreport
          pip3 install junit2html

      - name: Analyze
        if: always()
        run: |
          flutter analyze
      
      - name: Test
        if: always()
        run: |
          export PATH="$PATH":"${FLUTTER_HOME}/bin/cache/dart-sdk/bin"
          export PATH="$PATH":"${FLUTTER_HOME}/.pub-cache/bin"
          type flutter
          ./test.sh ${TEST_OUTPUT_DIR}

      - name: Arcive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TEST_OUTPUT_DIR }}
          path: ${{ env.TEST_OUTPUT_DIR }}
